#pragma once
#include <stdint.h>

extern uint8_t last_error;

#define ERROR_OK 0
#define FAT_ERROR_NO_CARD 1
#define FAT_ERROR_UNSUPPORTED_FAT_TYPE 2
#define FAT_ERROR_UNSUPPORTED_SECTOR_SIZE 3
#define FAT_ERROR_TOO_MANY_FATS 4
#define FAT_ERROR_TOO_MANY_OPEN_FILES 5
#define FAT_ERROR_NOT_A_DIR 6
#define FAT_ERROR_CARD_REINSERTED 7
#define FAT_ERROR_CARD 8
#define FAT_ERROR_FS_BROKEN 9
#define FAT_ERROR_NOT_FOUND 10
#define FAT_ERROR_BAD_DESCRIPTOR 11
#define FAT_EOF 12
#define FAT_ERROR_RELATIVE_PATH 13
#define FAT_ERROR_IS_DIR 14
#define FAT_ERROR_STALE_DESCRIPTOR 15
#define FAT_ERROR_FILE_EXISTS 16
#define FAT_ERROR_DIR_FULL 17

#define EXEC_ERROR_WRONG_EXTENSION 64
#define EXEC_ERROR_FILE_TOO_LARGE 65
