Import("env", "app_env", "rom_env", "c_runtime", "app_startup", "rom_startup", "fpmath")

# Apps
mandelbrot_app = app_env.Program('mndlbrot', Split('main.c') + c_runtime + app_startup + fpmath, LIBS=['c', 'sys'])
mandelbrot16_app = app_env.Program('mndlbt16', Split('main16.c') + c_runtime + app_startup + fpmath, LIBS=['c', 'sys'])
fptest_bin = rom_env.Program('fptest', Split('fptest.c') + c_runtime + rom_startup + fpmath, LIBS=['c', 'sys'])
fptest16_bin = rom_env.Program('fptest16', Split('fptest16.c') + c_runtime + rom_startup + fpmath, LIBS=['c', 'sys'])

Return("mandelbrot_app mandelbrot16_app")
