Import("env", "app_env", "rom_env", "c_runtime", "app_startup", "rom_startup")

fixpoint = env.Object(Split('fp32_28_umul.asm fp16_12_umul.asm fixpoint.c'))

# Apps
mandelbrot_app = app_env.Program('mndlbrot', Split('main.c') + c_runtime + app_startup + fixpoint, LIBS=['c', 'sys'])
mandelbrot16_app = app_env.Program('mndlbt16', Split('main16.c') + c_runtime + app_startup + fixpoint, LIBS=['c', 'sys'])
fptest_bin = rom_env.Program('fptest', Split('fptest.c') + c_runtime + rom_startup + fixpoint, LIBS=['c', 'sys'])
fptest16_bin = rom_env.Program('fptest16', Split('fptest16.c') + c_runtime + rom_startup + fixpoint, LIBS=['c', 'sys'])

Return("mandelbrot_app mandelbrot16_app")
